online_shop/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from core.views import CustomerRegisterView, CustomerLoginView, logout_view
from home import views

urlpatterns = i18n_patterns(
    path("", include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('register/', CustomerRegisterView.as_view(), name='register-customer'),
    path('login/', CustomerLoginView.as_view(), name='login-customer'),
    path('logout/', logout_view, name='logout-customer'),
    path('order/', include('order.urls', namespace='order')),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('pay/successful/', views.PayView.as_view(), name="pay_successful"),
    path('close/successful/', views.CloseView.as_view(), name="close_successful"),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/product/urls.py
from django.urls import path
from . import api_views
from . import views

app_name = "product"
urlpatterns = [
    path("<int:pk>/", views.ProductDetailView.as_view(), name="detail"),
    path('category/<int:category_id>/', views.CategoryProductView.as_view(), name="category"),
    path('brand/<int:brand_id>/', views.BrandProductView.as_view(), name="brand"),
    path('<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('api/list/', api_views.ProductListAPI.as_view(), name="list_api"),
    path('api/add_to_cart/', api_views.AddToCart.as_view(), name="add_to_cart"),
    path('get_cart/', api_views.GetCart.as_view(), name="get_cart"),
    path('delet_from_cart/', api_views.DeleteFromCart.as_view(), name="delete_from_cart"),
    # path("list_api/", views.ProductListAPI.as_view(), name="product_list_api"),
    # path("api/<int:pk>", views.ProductDetailAPI.as_view(), name="product_detail_api"),
]

online_shop/home/models.py
from django.db import models

# Create your models here.

online_shop/home/views.py
from django.views import View
from django.shortcuts import render
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from product.models import Product, Category, Brand
from order.models import Order, OrderItem


class HomeView(View):
    def get(self, request):
        products = Product.objects.all()
        categories = Category.parents()
        brands = Brand.objects.all()
        context = {
            "products": products,
            "categories": categories,
            "brands": brands,
        }
        return render(request, template_name="product/home.html", context=context)


class CartView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        customer = request.user.customer
        addresses = customer.address_set.all()
        try:
            order = customer.order_set.get(is_open=True)
        except:
            order = Order.objects.create(customer=customer, address=customer.address_set.first())
            data: dict = request.session.get("cart", {})
            for product_id, data in data.items():
                number = data["number"]
                product = Product.objects.get(id=product_id)
                order_item = OrderItem.objects.create(order=order, product=product, number=number)
            order.save()

        products = Product.objects.all()
        categories = Category.parents()
        brands = Brand.objects.all()
        context = {
            "order": order,
            "addresses": addresses,
            "products": products,
            "categories": categories,
            "brands": brands,
        }
        return render(request, template_name="home/cart_home.html", context=context)


class PayView(LoginRequiredMixin, View):
    def get(self, request):
        customer = request.user.customer
        order = customer.order_set.get(is_open=True)

        order.is_open = False
        order.is_paid = True
        order.save()

        request.session.pop('cart')

        categories = Category.parents()
        brands = Brand.objects.all()
        context = {
            "categories": categories,
            "brands": brands,
        }
        return render(request=request,
                      template_name="home/pay_successful.html",
                      context=context)


class CloseView(LoginRequiredMixin, View):
    def get(self, request):
        customer = request.user.customer
        order = customer.order_set.get(is_open=True)

        order.is_open = False
        order.is_paid = False
        order.save()

        request.session.pop('cart')

        categories = Category.parents()
        brands = Brand.objects.all()
        context = {
            "categories": categories,
            "brands": brands,
        }
        return render(request=request,
                      template_name="home/close_successful.html",
                      context=context)

online_shop/templates/home/cart_home.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}

{% block extera_css %}
    <style>
        .li-item {
            height: 6rem;
        }

        img {

        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8 col-12 p-2">
                <ul class="list-group">
                    {% for orderitem in order.orderitem_set.all %}
                        <li class="list-group-item li-item" id="{{ orderitem.product.id }}">
                            <a href="{% url "product:product_detail" orderitem.product.id %}"><img class="h-100" src="{{ orderitem.product.image.url }}" alt=""></a>
                            {{ orderitem.number }}{% translate "x" %} - {{ orderitem.product.name }}
                            {% translate "Price" %}:
                            {% with product=orderitem.product %}
                                {% if product.discount %}
                                    <b>{{ product.final_price }} {% translate "Toman" %}</b>
                                    <i style="color: red">
                                        {{ product.discount.amount }}{% if product.discount.type == "PER" %}%{% else %}
                                            {% translate "Toman" %}{% endif %}{% translate " Off" %}</i>
                                    <del><i>{{ product.price }} {% translate "Toman" %}</i></del>
                                {% else %}
                                    <b>{{ product.price }} {% translate "Toman" %}</b>
                                {% endif %}
                            {% endwith %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-lg-4 col-12 p-2">
                {#                <div class="row w-100 m-0">#}
                {#                    <div class="input-group mb-3">#}
                {#                        <input type="text" class="form-control" placeholder="{% translate "Off Code" %}"#}
                {#                               aria-label="Recipient's username" aria-describedby="button-addon2">#}
                {#                        <button class="btn btn-outline-success" type="button"#}
                {#                                id="button-addon2">{% translate "Use" %}</button>#}
                {#                    </div>#}
                {#                </div>#}

                <div class="row w-100 m-0 mb-2">
                    <div class="dropdown w-100">
                        <button class="btn btn-secondary dropdown-toggle w-100" type="button" id="dropdownMenu2"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            {% translate "Addresses" %}
                        </button>
                        <ul class="dropdown-menu w-auto" aria-labelledby="dropdownMenu2">
                            {% for address in addresses %}
                                <li>
                                    <button id="address-{{ address.id }}" class="dropdown-item" type="button"
                                            onclick="addressChange(this)">
                                        {{ address }}
                                    </button>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <p class="w-auto align-self-center m-0"
               id="final-price">{% translate "Final Price" %}: {{ order.total_price }} {% translate "Toman" %}</p>

            <div class="dropdown w-auto">
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    {% translate "Pay" %}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{% url "pay_successful" %}">{% translate "Online" %}</a></li>
                    <li><a class="dropdown-item" href="{% url "close_successful" %}">{% translate "On Location" %}</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

online_shop/templates/home/close_successful.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container m-0 justify-content-center">
    <div class="row m-0 ">
        <h1>{% translate "Thank you for your purchase." %}</h1>
        <a href="{% url "home:home" %}" class="btn btn-primary">{% translate "Back to Online-Shop" %}</a>
    </div>
    </div>
{% endblock %}

online_shop/templates/home/pay_successful.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="container m-0 justify-content-center">
    <div class="row m-0 ">
        <h1>{% translate "Your order has been successfully paid." %}</h1>
        <h2>{% translate "Thank you for your purchase." %}</h2>
        <a href="{% url "home:home" %}" class="btn btn-primary">{% translate "Back to Online-Shop" %}</a>
    </div>
    </div>
{% endblock %}