online_shop/customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"
urlpatterns = [
    path("order_history/", views.OrderHistoryView.as_view(), name="order-history"),
    path("order_history/<int:pk>", views.OrderHistoryListView.as_view(), name="order-items"),
    # path("order_status/", views.OrderStatusView.as_view(), name="order-status"),
    path("address/", views.AddressView.as_view(), name="address"),
    path("address/add/", views.AddAddressView.as_view(), name="add-address"),
    path("address/edit/<int:pk>", views.EditAddressView.as_view(), name="edit-address"),
    path("address/delete/<int:address_id>", views.DeleteAddressView.as_view(), name="delete-address"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("profile/password/change/", views.PasswordChangeView.as_view(), name="password-change"),
    path("address_api/<int:pk>", views.AddressDetailView.as_view()),
    path("address_list_api/", views.AddressListView.as_view()),
]

online_shop/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from core.views import CustomerRegisterView, CustomerLoginView, logout_view
from home import views

urlpatterns = i18n_patterns(
    path("", include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('register/', CustomerRegisterView.as_view(), name='register-customer'),
    path('login/', CustomerLoginView.as_view(), name='login-customer'),
    path('logout/', logout_view, name='logout-customer'),
    path('order/', include('order.urls', namespace='order')),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('pay/successful/', views.PayView.as_view(), name="pay_successful"),
    path('close/successful/', views.CloseView.as_view(), name="close_successful"),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/order/urls.py
from django.urls import path, include
from . import views

app_name = "order"
urlpatterns = [
    path("address_change/", views.AddressChange.as_view(), name="address_change"),
]

online_shop/product/urls.py
from django.urls import path
from . import api_views
from . import views

app_name = "product"
urlpatterns = [
    path("<int:pk>/", views.ProductDetailView.as_view(), name="detail"),
    path('category/<int:category_id>/', views.CategoryProductView.as_view(), name="category"),
    path('brand/<int:brand_id>/', views.BrandProductView.as_view(), name="brand"),
    path('<int:pk>/', views.ProductDetailView.as_view(), name="product_detail"),
    path('api/list/', api_views.ProductListAPI.as_view(), name="list_api"),
    path('api/add_to_cart/', api_views.AddToCart.as_view(), name="add_to_cart"),
    path('get_cart/', api_views.GetCart.as_view(), name="get_cart"),
    path('delet_from_cart/', api_views.DeleteFromCart.as_view(), name="delete_from_cart"),
    # path("list_api/", views.ProductListAPI.as_view(), name="product_list_api"),
    # path("api/<int:pk>", views.ProductDetailAPI.as_view(), name="product_detail_api"),
]

online_shop/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


class MyUserManager(UserManager):

    def create_user(self, username=None, email=None, password=None, **extra_fields):
        username = extra_fields["phone"]
        return super().create_user(username, email, password, **extra_fields)

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        username = extra_fields["phone"]
        return super().create_superuser(username, email, password, **extra_fields)


class User(AbstractUser):
    objects = MyUserManager()

    phone = models.CharField(max_length=15, unique=True)
    USERNAME_FIELD = "phone"


class BaseManager(models.Manager):

    def full_archive(self):
        return super().get_queryset()

    def get_queryset(self):
        return super().get_queryset().filter(is_delete=False)


class BaseModel(models.Model):
    class Meta:
        abstract = True

    objects = BaseManager()

    is_delete = models.BooleanField(default=False, editable=False, db_index=True)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save(using=using)

    def restore(self):
        self.is_delete = False
        self.save()

online_shop/core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import User


# class LoginForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ["phone", "password"]
#
#         labels = {
#             'phone': _("Phone Number"),
#             'password': _("Password"),
#         }
#
#         widgets = {
#             'phone': forms.TextInput(attrs={'placeholder': _("Example: 09123456789")}),
#             'password': forms.PasswordInput(),
#         }


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=15, label=_("Phone"))
    password = forms.CharField(max_length=100, label=_("Password"), widget=forms.PasswordInput)

online_shop/core/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect
from django.contrib import messages
from django.utils.translation import gettext_lazy as _

from django.views import View
from core.models import User
from customer.forms import UserForm
from core.forms import LoginForm


class CustomerRegisterView(View):
    def get(self, request):
        form = UserForm()
        context = {
            "form": form,
        }
        return render(request=request, template_name="core/customer_register.html",
                      context=context)

    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            phone = request.POST['phone']
            password = request.POST['password']
            user: User = User.objects.create_user(phone=phone, password=password)
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            user = authenticate(request, phone=phone, password=password)
            login(request, user)
            return redirect("customer:profile")
        else:
            context = {
                "form": form,
            }
            return render(request=request, template_name="core/customer_register.html", context=context)


class CustomerLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect("customer:profile")
        form = LoginForm()
        context = {
            "form": form,
        }
        return render(request=request, template_name="core/login_customer.html", context=context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            phone = request.POST['phone']
            password = request.POST['password']
            user = authenticate(request, phone=phone, password=password)
            if user is not None:
                login(request, user)
                return redirect("customer:profile")
            else:
                messages.error(request, _("Phone or password is incorrect."), "danger")
                return redirect("login-customer")

        context = {
            "form": form,
        }
        return render(request=request, template_name="core/login_customer.html", context=context)


def logout_view(request):
    if request.method == "GET":
        logout(request)
        messages.success(request, _("User logged out successfully."), "success")
        return redirect("login-customer")

online_shop/templates/core/includes/_jquery.html
{% load i18n %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    function AddToCart(elem) {
        let product_id = $(elem).parent().parent().parent().parent().attr('id')
        let number = $(elem).parent().find('.item-number').val()
        console.log(product_id, number)
        $.ajax({
                url: '{% url "product:add_to_cart" %}',
                type: 'GET',
                data: {
                    'product_id': product_id,
                    'number': number,
                },
                success: function (result) {
                    console.log(number + ' ' + result['name'] + 'added to cart.')
                    updateCart()
                },
                error: function () {
                    console.log('Error!')
                }
            }
        )
    }

    function updateCart() {
        $.ajax({
                url: '{% url "product:get_cart" %}',
                type: 'GET',
                data: {},
                success: function (result) {
                    console.log(result)
                    let row
                    let cart_html = ''
                    Object.keys(result).forEach(key => {
                        let product = result[key]
                        let delete_button = '<a href="#" id="delete-' + key + '" onclick="deleteFromCart(this)" class="ms-1 btn btn-danger">{% translate "Del" %}</a>'
                        row = '<li class="dropdown-item">' + product.number + ' of ' + product.name + delete_button + '</li>'
                        cart_html = cart_html + row
                    })
                    if (cart_html === '') {
                        cart_html = '<li class="dropdown-item">{% translate "Cart is empty." %}</li>'
                    }
                    cart_html = cart_html + '<li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-center bg-warning rounded" href="{% url "cart" %}">{% translate "Pay" %}</a></li>'
                    $("#cart-ul").html(cart_html)
                },
                error: function () {
                    console.log('Error!')
                }
            }
        )
    }

    function deleteFromCart(elem) {
        let product_id = $(elem).attr("id").slice(7)
        $.ajax({
                url: '{% url "product:delete_from_cart" %}',
                type: 'GET',
                data: {
                    "product_id": product_id
                },
                success: function (result) {
                    alert(result['msg'])
                    updateCart()
                },
                error: function () {
                    console.log('Error!')
                }
            }
        )
        if ($('.li-item').length) {
            $('#' + product_id).remove()
        }
    }

    function addressChange(elem) {
        let address_id = $(elem).attr("id").slice(8)
        $.ajax({
                url: '{% url "order:address_change" %}',
                type: 'GET',
                data: {
                    "address_id": address_id
                },
                success: function (result) {
                    alert(result['msg'])
                },
                error: function () {
                    console.log('Error!')
                }
            }
        )
    }
</script>

online_shop/templates/core/includes/cart.html
{% load i18n %}

<div class="btn-group">
    <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        {% translate "Cart" %}
    </button>
    <ul class="dropdown-menu" id="cart-ul">
        {% if request.session.cart %}
            {% for product_id, product in request.session.cart.items %}
                <li class="dropdown-item">{{ product.number }} of {{ product.name }}
                    <a href="#" id="delete-{{ product_id }}" onclick="deleteFromCart(this)"
                       class="ms-1 btn btn-danger">{% translate "Del" %}</a></li>
            {% endfor %}
        {% else %}
            <li class="dropdown-item">{% translate "Cart is empty." %}</li>
        {% endif %}
        <li>
            <hr class="dropdown-divider">
        </li>
        <li><a class="dropdown-item text-center bg-warning rounded" href="{% url "cart" %}">{% translate "Pay" %}</a></li>
    </ul>
</div>

online_shop/templates/core/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }} m-3">{{ message }}</p>
    {% endfor %}
{% endif %}

online_shop/templates/core/includes/navbar.html
{% load i18n %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="#">
        <img src="{% static "logo/logo.png" %}" alt="" width="30" height="24"
             class="d-inline-block align-text-top">
        {% translate "Online Shop" %}
    </a>

    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url "home:home" %}">{% translate "Home" %}</a>
                </li>
                {% if categories %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% translate "Categories" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for category in categories %}
                                <li><a class="dropdown-item"
                                       href="{% url "product:category" category.id %}">{{ category.name }}</a></li>
                                {% for child in category.children %}
                                    <li>
                                        <a class="dropdown-item"
                                           href="{% url "product:category" child.id %}">> {{ child.name }}</a>
                                    </li>
                                {% endfor %}
                                {% if not forloop.last %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% translate "Brands" %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for brand in brands %}
                                <li>
                                    <a class="dropdown-item" href="{% url "product:brand" brand.id %}">{{ brand.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
{#            {% include "core/includes/cart.html" %}#}
            </ul>

            {% include "core/includes/cart.html" %}
            {% if request.user.is_authenticated %}
                <div class="dropdown">
                    <a class="btn ms-2 btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.first_name | title }}
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item"
                               href="{% url "customer:profile" %}">{% translate "My Profile" %}</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url "customer:address" %}">{% translate "Addresses" %}</a></li>
                        <li><a class="dropdown-item"
                               href="{% url "customer:order-history" %}">{% translate "Orders" %}</a></li>
                        <li><a class="dropdown-item"
                               href="{% url "logout-customer" %}">{% translate "Logout" %}</a></li>
                    </ul>
                </div>
            {% else %}
                <a class="btn btn-success ms-2" aria-current="page"
                   href="{% url "register-customer" %}">{% translate "Register" %}</a>
                <a class="btn btn-outline-primary ms-2" aria-current="page"
                   href="{% url "login-customer" %}">{% translate "Login" %}</a>
            {% endif %}
        </div>
    </div>
</nav>

online_shop/templates/core/includes/product_home_view.html
{% load i18n %}

<div id="{{ product.id }}" class="card col-md-3 col-5 p-1 text-center" style="background: #ededed">
    <a href="{% url "product:detail" product.id %}" style="text-decoration: None;">
        <img style="object-fit: cover; height: 14rem;" src="{{ product.image.url }}" class="card-img-top"
             alt="product-{{ product.id }}"></a>
    <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        {#        <p class="card-text">{{ product.detail|truncatechars:20 }}</p>#}
        {% if product.discount %}
            <h6 style="color: red">{{ product.discount.amount }}{% if product.discount.type == "PER" %}%{% else %}
                {% translate "Toman" %}{% endif %}{% translate " Off" %}</h6>
            <del><h6 class="card-text">{{ product.price }} {% translate "Toman" %}</h6></del>
            <h5 class="card-text">{{ product.final_price }} {% translate "Toman" %}</h5>
        {% else %}
            <h5 class="card-text">{{ product.price }} {% translate "Toman" %}</h5>
        {% endif %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                {# <a href="#" class="col-auto btn btn-outline-danger">{% translate "-" %}</a>#}
                 <input class="col-md-4 col-auto text-center item-number" type="number" min="0" value="1">
                <div class="col-auto btn btn-outline-success" onclick="AddToCart(this)">{% translate "Add" %}</div>

                <a href="{% url "product:detail" product.id %}"
                   class="col-auto btn btn-info ms-2">{% translate "Info" %}</a>
            </div>
        </div>
    </div>
</div>