online_shop/customer/urls.py
from django.urls import path
from customer import views

app_name = "customer"
urlpatterns = [
    path("order_history/", views.OrderHistoryView.as_view(), name="order-history"),
    path("order_history/<int:pk>", views.OrderHistoryListView.as_view(), name="order-items"),
    # path("order_status/", views.OrderStatusView.as_view(), name="order-status"),
    path("address/", views.AddressView.as_view(), name="address"),
    path("address/add/", views.AddAddressView.as_view(), name="add-address"),
    path("address/edit/<int:pk>", views.EditAddressView.as_view(), name="edit-address"),
    path("address/delete/<int:address_id>", views.DeleteAddressView.as_view(), name="delete-address"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile-update"),
    path("profile/password/change/", views.PasswordChangeView.as_view(), name="password-change"),
    path("address_api/<int:pk>", views.AddressDetailView.as_view()),
    path("address_list_api/", views.AddressListView.as_view()),
]

online_shop/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home")
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

from core.views import CustomerRegisterView, CustomerLoginView, logout_view
from home import views

urlpatterns = i18n_patterns(
    path("", include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('register/', CustomerRegisterView.as_view(), name='register-customer'),
    path('login/', CustomerLoginView.as_view(), name='login-customer'),
    path('logout/', logout_view, name='logout-customer'),
    path('order/', include('order.urls', namespace='order')),
    path('cart/', views.CartView.as_view(), name="cart"),
    path('pay/successful/', views.PayView.as_view(), name="pay_successful"),
    path('close/successful/', views.CloseView.as_view(), name="close_successful"),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/customer/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import User, BaseModel


class Customer(models.Model):
    """
        # TODO: Add docstring
    """
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    # first_name = models.CharField(max_length=100)
    # last_name = models.CharField(max_length=100)

    # def full_name(self):
    #     return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

    class Meta:
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")
        permissions = [
            ("being_customer", "is a customer."),
        ]


class Address(BaseModel):
    """
        # TODO: Add docstring
    """
    customer = models.ForeignKey(to="Customer", null=True, on_delete=models.SET_NULL)
    province = models.CharField(max_length=100)  # TODO: Add choices for each province in Iran.
    city = models.CharField(max_length=100)  # TODO: Add choices for each city of selected province.
    detail = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.province}, {self.city}, {self.detail}"

    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

online_shop/customer/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError

from customer.models import Customer
from core.models import User
from core.validators import check_phone


class CustomerRegisterForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ['user', ]

        labels = {
            'first_name': _("First Name"),
            'last_name': _("Last Name"),
        }


class UserForm(forms.ModelForm):  # TODO: add re-enter password
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Confirm Password")

    class Meta:
        model = User
        # fields = "__all__"
        fields = ["phone", "password"]

        labels = {
            'phone': _("Phone Number"),
            'password': _("Password"),
            'password2': _("Confirm Password"),
        }

        widgets = {
            'phone': forms.TextInput(attrs={'placeholder': _("Example: 09123456789")}),
            'password': forms.PasswordInput(),
        }

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        return check_phone(phone)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] and cd["password2"] and cd["password"] != cd["password2"]:
            raise ValidationError(_("Passwords does not match."))
        return cd["password2"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone", "email"]

        labels = {
            'first_name': _("First Name"),
            'last_name': _("Last Name"),
            'phone': _("Phone Number"),
            'email': _("Email"),
        }


class ChangePasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        labels = {
            'new_password': _("New Password"),
        }

online_shop/customer/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from rest_framework import generics, permissions, authentication

from django.views import View
from django.views.generic import UpdateView, ListView, DetailView, CreateView

from core.models import User
from customer.models import Customer, Address
from customer.forms import ProfileForm, ChangePasswordForm
from order.models import Order
from customer.serializers import AddressSerializer, UserSerializer
from customer.permissions import IsOwnerPermission, IsSuperuserPermission


class ProfileView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        if not request.user.is_authenticated:
            # TODO: add an error message
            return HttpResponseRedirect(reverse("login-customer"))
        user = request.user
        customer = Customer.objects.get(user_id=user.id)
        context = {
            "customer": customer,
        }
        return render(request=request, template_name="customer/customer_profile.html", context=context)


class AddressView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        customer = request.user.customer
        addresses = Address.objects.filter(customer=customer)
        context = {
            "addresses": addresses,
            "customer": customer,
        }
        return render(request=request, template_name="customer/customer_address.html", context=context)


class ProfileUpdateView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        user = request.user
        form = ProfileForm(instance=user)
        context = {
            "form": form,
        }
        return render(request=request, template_name="customer/customer_update.html", context=context)

    def post(self, request):
        user = request.user
        data = request.POST
        user.phone = data['phone']
        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.email = data['email']
        user.save()
        return HttpResponseRedirect(reverse("customer:profile"))


class OrderHistoryView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        user = request.user
        customer = user.customer
        orders = Order.objects.filter(customer=customer)
        context = {
            "orders": orders,
        }
        return render(request=request, template_name="customer/customer_order_history.html", context=context)


class OrderHistoryListView(PermissionRequiredMixin, DetailView):
    permission_required = "customer.being_customer"
    model = Order
    template_name = "customer/order_items.html"


# class UserListView()
# class UserDetailView()

class AddressListView(generics.ListAPIView):
    model = Address
    serializer_class = AddressSerializer
    queryset = Address.objects.all()
    permissions = [IsSuperuserPermission]
    authentication = [authentication.BasicAuthentication]


class AddressDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = AddressSerializer
    queryset = Address.objects.all()
    permissions = [IsOwnerPermission]
    authentication_classes = [authentication.BasicAuthentication]


class PasswordChangeView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request):
        form = ChangePasswordForm()
        context = {
            "form": form
        }
        return render(request=request, template_name="customer/change_password.html", context=context)

    def post(self, request):
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            user = request.user
            new_password = form.cleaned_data["new_password"]
            user.set_password(new_password)
            user.save()
            messages.success(request, _("Password changed successfully."), "success")
            login(request, user)
            return redirect("customer:profile")
        else:
            context = {
                "form": form
            }
            messages.error(request, _("Enter a valid password."), "danger")
            return render(request=request, template_name="customer/change_password.html", context=context)


class AddAddressView(PermissionRequiredMixin, CreateView):
    permission_required = "customer.being_customer"

    model = Address
    fields = ["province", "city", "detail"]
    template_name = "customer/add_address.html"
    success_url = reverse_lazy("customer:address")

    def form_valid(self, form):
        address = form.save(commit=False)
        customer = Customer.objects.get(user=self.request.user)
        address.customer = customer
        address.save()
        messages.success(self.request, _("Address successfully added."), "success")
        return super().form_valid(form)


class EditAddressView(PermissionRequiredMixin, UpdateView):
    permission_required = "customer.being_customer"

    model = Address
    fields = ["province", "city", "detail"]
    template_name = "customer/edit_address.html"
    success_url = reverse_lazy("customer:address")


class DeleteAddressView(PermissionRequiredMixin, View):
    permission_required = "customer.being_customer"

    def get(self, request, address_id):
        Address.objects.get(id=address_id).delete()
        messages.success(request, _("Address Deleted."), "success")
        return redirect("customer:address")

online_shop/templates/customer/add_address.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Add Address" %}{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    <input type="submit" class="btn btn-primary" value="{% translate "Add" %}">
    </form>
{% endblock %}

online_shop/templates/customer/change_password.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Change Password" %}{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input class="btn btn-primary" type="submit" value="Change">
    </form>
{% endblock %}

online_shop/templates/customer/customer_address.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Customer Addresses" %}{% endblock %}
{% block content %}
    <a class="btn btn-primary mb-5" href="{% url "customer:add-address" %}"><b>+ </b>{% translate "Add Address" %}</a>
    <div class="container">
        <div class="row justify-content-around">
            {% for address in addresses %}
                <div class="card w-25 m-1">
                    <div class="card-body">
                        <h5 class="card-title">{{ address.province }}-{{ address.city }}</h5>
                        <p class="card-text">{{ address.detail }}</p>
                        <a href="{% url "customer:edit-address" address.id %}" class="btn btn-warning">{% translate "Edit" %}</a>
                        <a href="{% url "customer:delete-address" address.id %}" class="btn btn-danger">{% translate "Delete" %}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

online_shop/templates/customer/customer_order_history.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Customer Order History" %}{% endblock %}
{% block content %}
    {#    <ul>#}
    {#        {% for order in orders %}#}
    {#            <li><a href="{% url "customer:order-items" order.id %}">{{ order }}</a></li>#}
    {#            <ul>#}
    {#                <li>{% translate "Paid: " %}{{ order.is_paid }}</li>#}
    {#            </ul>#}
    {#        {% endfor %}#}
    {#    </ul>#}

    <div class="container">
        <div class="row justify-content-center">
            {% for order in orders %}
                <div class="card w-auto m-1">
                    <a style="text-decoration: None; color: black;" href="{% url "customer:order-items" order.id %}">
                        <div class="card-body">
                            <h3>Order {{ forloop.counter }}</h3>
                            <p class="card-text">
                                {% translate "to: " %} {{ order.address.province }}-{{ order.address.city }}</p>
                            <p>{% translate "Price:" %} <b>{{ order.total_price }}</b></p>
                            <p class="card-text">{% if order.is_paid %}
                                <a class="btn btn-success disabled w-100" href="#">{% translate "Paid" %}</a>
                            {% else %}
                                <a class="btn btn-danger w-100" href="#">{% translate "Pay" %}</a>
                            {% endif %}
                            </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

online_shop/templates/customer/customer_profile.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Customer Profile" %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card w-auto m-1 align-items-center">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{% translate "First Name: " %}{{ customer.user.first_name }}</li>
                    <li class="list-group-item">{% translate "Last Name: " %}{{ customer.user.last_name }}</li>
                    <li class="list-group-item">{% translate "Phone Number: " %}{{ customer.user.phone }}</li>
                    <li class="list-group-item">{% translate "Email: " %}{{ customer.user.email }}</li>
                </ul>
                <a class="btn btn-primary w-50 my-2" href="{% url "customer:profile-update" %}">{% translate "Edit Profile" %}</a>
            </div>
        </div>
    </div>
{% endblock %}

online_shop/templates/customer/customer_update.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Customer Profile Update" %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="card w-auto m-1 align-items-center">
                <form class="m-2" action="{% url "customer:profile-update" %}" method="POST">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>
                    <input class="btn btn-primary mt-3" type="submit" value="Update">
                    <a class="btn btn-warning align-self-end mt-3" href="{% url "customer:password-change" %}">Change Password</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

online_shop/templates/customer/edit_address.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Edit Address" %}{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
    <input type="submit" class="btn btn-primary" value="{% translate "Edit" %}">
    </form>
{% endblock %}

online_shop/templates/customer/order_items.html
{% extends "core/base.html" %}
{% load static %}
{% load i18n %}


{% block title %}{% translate "Order " %}{{ order.id }}{% translate "itmes" %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <p>{% translate "Address: " %}{{ order.address }}</p>
            <div class="card w-auto m-1 align-items-center">
                <p class="mt-2">Items:</p>
                <ul class="list-group list-group-flush">
                    {% for order_item in order.orderitem_set.all %}
                        <li class="list-group-item">
                            {{ order_item.number }}{% translate " of " %}{{ order_item.product }}</li>
                    {% endfor %}
                    <li class="list-group-item">{% translate "Price:" %} <b>{{ order.total_price }}</b></li>
                    <li class="list-group-item">
                        {% if order.is_paid %}
                            <a class="btn btn-success w-100 disabled" href="#">Paid</a>
                        {% else %}
                            <a class="btn btn-danger w-100" href="#">Pay</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}